# datasource config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url : jdbc:mysql://localhost:3306/comprehensive
    username: ohgiraffers
    password: ohgiraffers

# jpa config
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# server port
server:
  port: 8001

# image file
image:
  image-url: http://localhost:8001/productimgs/
  image-dir: src/main/resources/static/productimgs

# jwt setting
jwt:
  secret: asdfjp298pafo1320efqw0udvnh0er0h412r08byfdq9dsvh02143908hfeqwn80fdqs0nfdqs0n412013rq0nqefn08dfas0das730732g86923
  access:
    expiration: 3600000 #1시간
  refresh:
    expiration: 640800000



